# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: project/project.proto

require 'google/protobuf'


descriptor_data = "\n\x15project/project.proto\x12\x0c\x64\x65mo_project\"5\n\x14\x43reateProjectRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"E\n\x10\x43reateTagRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x12\n\nproject_id\x18\x03 \x01(\t\"8\n\x11GetProjectRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\nproject_id\x18\x02 \x01(\t\"T\n\x0fProjectResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\'\n\x04tags\x18\x03 \x03(\x0b\x32\x19.demo_project.TagResponse\";\n\x0bTagResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x12\n\nproject_id\x18\x03 \x01(\t2\xf6\x01\n\nProjectSvc\x12R\n\rcreateProject\x12\".demo_project.CreateProjectRequest\x1a\x1d.demo_project.ProjectResponse\x12\x46\n\tcreateTag\x12\x1e.demo_project.CreateTagRequest\x1a\x19.demo_project.TagResponse\x12L\n\ngetProject\x12\x1f.demo_project.GetProjectRequest\x1a\x1d.demo_project.ProjectResponseB6Z4github.com/Joker666/microservice-demo/protos/projectb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module DemoProject
  CreateProjectRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("demo_project.CreateProjectRequest").msgclass
  CreateTagRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("demo_project.CreateTagRequest").msgclass
  GetProjectRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("demo_project.GetProjectRequest").msgclass
  ProjectResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("demo_project.ProjectResponse").msgclass
  TagResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("demo_project.TagResponse").msgclass
end
