# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user/user.proto

require 'google/protobuf'


descriptor_data = "\n\x0fuser/user.proto\x12\tdemo_user\"\x1e\n\rVerifyRequest\x12\r\n\x05token\x18\x01 \x01(\t\"!\n\x0eGetUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"/\n\x0cLoginRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"@\n\x0fRegisterRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\"F\n\x0cUserResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\r\n\x05token\x18\x04 \x01(\t\"9\n\x0eVerifyResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t2\x85\x02\n\x07UserSvc\x12?\n\x08register\x12\x1a.demo_user.RegisterRequest\x1a\x17.demo_user.UserResponse\x12\x39\n\x05login\x12\x17.demo_user.LoginRequest\x1a\x17.demo_user.UserResponse\x12=\n\x06verify\x12\x18.demo_user.VerifyRequest\x1a\x19.demo_user.VerifyResponse\x12?\n\x07getUser\x12\x19.demo_user.GetUserRequest\x1a\x19.demo_user.VerifyResponseB3Z1github.com/Joker666/microservice-demo/protos/userb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module DemoUser
  VerifyRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("demo_user.VerifyRequest").msgclass
  GetUserRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("demo_user.GetUserRequest").msgclass
  LoginRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("demo_user.LoginRequest").msgclass
  RegisterRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("demo_user.RegisterRequest").msgclass
  UserResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("demo_user.UserResponse").msgclass
  VerifyResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("demo_user.VerifyResponse").msgclass
end
