# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task/task.proto

require 'google/protobuf'

require 'project/project_pb'
require 'user/user_pb'


descriptor_data = "\n\x0ftask/task.proto\x12\tdemo_task\x1a\x15project/project.proto\x1a\x0fuser/user.proto\"P\n\x10ListTasksRequest\x12\x12\n\nproject_id\x18\x01 \x01(\t\x12\x0e\n\x06tag_id\x18\x02 \x01(\t\x12\x18\n\x10\x61ssigned_user_id\x18\x03 \x01(\t\"p\n\x11\x43reateTaskRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x12\n\nproject_id\x18\x03 \x01(\t\x12\x0e\n\x06tag_id\x18\x04 \x01(\t\x12\x18\n\x10\x61ssigned_user_id\x18\x05 \x01(\t\"_\n\x11UpdateTaskRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0f\n\x07task_id\x18\x02 \x01(\t\x12\x0e\n\x06tag_id\x18\x03 \x01(\t\x12\x18\n\x10\x61ssigned_user_id\x18\x04 \x01(\t\";\n\x11ListTasksResponse\x12&\n\x05tasks\x18\x01 \x03(\x0b\x32\x17.demo_task.TaskResponse\"\x81\x02\n\x0cTaskResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x12\n\nproject_id\x18\x04 \x01(\t\x12\x0e\n\x06tag_id\x18\x05 \x01(\t\x12\x18\n\x10\x61ssigned_user_id\x18\x06 \x01(\t\x12.\n\x07project\x18\x07 \x01(\x0b\x32\x1d.demo_project.ProjectResponse\x12&\n\x03tag\x18\x08 \x01(\x0b\x32\x19.demo_project.TagResponse\x12\x30\n\rassigned_user\x18\t \x01(\x0b\x32\x19.demo_user.VerifyResponse2\xdb\x01\n\x07TaskSvc\x12\x43\n\ncreateTask\x12\x1c.demo_task.CreateTaskRequest\x1a\x17.demo_task.TaskResponse\x12\x43\n\nupdateTask\x12\x1c.demo_task.UpdateTaskRequest\x1a\x17.demo_task.TaskResponse\x12\x46\n\tlistTasks\x12\x1b.demo_task.ListTasksRequest\x1a\x1c.demo_task.ListTasksResponseB3Z1github.com/Joker666/microservice-demo/protos/taskb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module DemoTask
  ListTasksRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("demo_task.ListTasksRequest").msgclass
  CreateTaskRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("demo_task.CreateTaskRequest").msgclass
  UpdateTaskRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("demo_task.UpdateTaskRequest").msgclass
  ListTasksResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("demo_task.ListTasksResponse").msgclass
  TaskResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("demo_task.TaskResponse").msgclass
end
