apiVersion: v1
kind: ConfigMap

metadata:
  name: user-config
  namespace: shopforge

#This is user configuration ./UserService/.env files
data:
  DB_URI: "mongodb://mongodb:27017/"
  DB_NAME: "Microservice-demo-user"
  TOKEN_LIFE: "3600000000"
  HOST: "0.0.0.0"
  PORT: "50051"