apiVersion: v1
kind: Secret

metadata:
  name: user-secret
  namespace: shopforge

type: Opaque

#This is user configuration ./UserService/.env files
stringData:
  TOKEN_SECRET: "microservicedemonodejs"